---
title: "nuDNA_PCA"
author: "Hannah Noel"
date: "2024-05-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(kableExtra)
library(dplyr)
library(FactoMineR)
library(factoextra)
library(ggplot2)

options(knitr.kable.NA = "")
```

```{r dataFrame, echo=FALSE}

df1 <- read.csv('nuDNA_environmental.csv')
df1$donor_id <- factor(df1$donor_id)

```

```{r modPCA, include=TRUE}
#setting up PCA of environmental factors 
mod.PCA <- PCA(
  df1[,2:7], 
  scale.unit = TRUE, 
  quali.sup = c(1), 
  graph = FALSE
  )
#table of eigen values and dimensions 
kbl(mod.PCA$eig, 
    digits = 3) |>
  kable_classic(full = FALSE)
#table of correlation coefficients 
kbl(mod.PCA$var$cor, 
    digits = 3) |>
  kable_classic(full = FALSE)
#visualizing PCA 
decomp1 <- fviz_pca_biplot(mod.PCA,
                axes = c(1,2),
                geom.ind = "point", 
                col.ind = df1$donor_id, 
                palette = c("blue","black","orange"),
                legend.title = "Donor",
                label = 'var',
                repel = TRUE) +
  theme_minimal(base_size = 10) +
  labs (x="Dimension 1 (41.507%)", y="Dimension 2 (25.965%)") 

decomp1 
```

```{r regressionMod, include=TRUE}

#combining dimensions of PCA with environmental factors 
df2 <- cbind(df1, mod.PCA$ind$coord)

#ANOVAs looking at significant relationships between dimensions of PCA and the quantity of nuDNA 
dim1Mod <- lm(quantity_nudna ~ Dim.1, df2)

anova(dim1Mod)

dim2Mod <- lm(quantity_nudna ~ Dim.2, df2)

anova(dim2Mod)

dim3Mod <- lm(quantity_nudna ~ Dim.3, df2) 

anova(dim3Mod)

#visualization of dimension 2 and quantity of nuDNA as a linear regression 
ggplot(df2, aes(x=Dim.2, y=quantity_nudna)) +
  geom_point() +
  scale_y_log10() + 
  geom_smooth(method="lm") + 
  labs (x="Dimension 2", y="Quantity of nuDNA (ng/uL)") 

```

